apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: laseris
  namespace: argocd
spec:
  destination:
    namespace: laseris-website
    server: https://kubernetes.default.svc
  source:
    path: prod/website
    repoURL: https://github.com/PTRRR/laseris-config
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
